/*
 * Raymond Gao, Are4Us technologies, http://are4.us
 * Copyright 2012
 */
package are4.us.mongo.gui;

import are4.us.mongo.core.MongoServerWrapper;
import are4.us.mongo.exception.AuthenticationException;
import java.awt.*;
import java.util.Map.Entry;
import javax.swing.*;
import are4.us.mongo.object.MongoServerConfig;
import are4.us.mongo.object.MongoServerConfigFactory;

/**
 *
 * @author raygao2000
 */
public class MongoAnalyzer extends JFrame {

    /**
     * Creates new form VultanAnalyzer
     */
    public MongoAnalyzer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelMain = new javax.swing.JPanel();
        jSplitPane = new javax.swing.JSplitPane();
        jPanelToolbar = new javax.swing.JPanel();
        jButtonAddServer = new javax.swing.JButton();
        jPanelServerList = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemPreference = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemQuit = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setTitle("MongoAnalyzer");
        setPreferredSize(new java.awt.Dimension(600, 530));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(200, 120));

        jSplitPane.setDividerLocation(320);
        jSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane.setResizeWeight(1.0);

        jPanelToolbar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolbar.setMinimumSize(new java.awt.Dimension(100, 75));
        jPanelToolbar.setPreferredSize(new java.awt.Dimension(500, 75));

        jButtonAddServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Plus__Orange.png"))); // NOI18N
        jButtonAddServer.setText("Add Server");
        jButtonAddServer.setFocusable(false);
        jButtonAddServer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddServer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAddServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddServerActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelToolbarLayout = new org.jdesktop.layout.GroupLayout(jPanelToolbar);
        jPanelToolbar.setLayout(jPanelToolbarLayout);
        jPanelToolbarLayout.setHorizontalGroup(
            jPanelToolbarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelToolbarLayout.createSequentialGroup()
                .addContainerGap()
                .add(jButtonAddServer)
                .addContainerGap(480, Short.MAX_VALUE))
        );
        jPanelToolbarLayout.setVerticalGroup(
            jPanelToolbarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelToolbarLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .add(jButtonAddServer)
                .addContainerGap())
        );

        jSplitPane.setBottomComponent(jPanelToolbar);

        jPanelServerList.setBorder(javax.swing.BorderFactory.createTitledBorder("Servers"));

        org.jdesktop.layout.GroupLayout jPanelServerListLayout = new org.jdesktop.layout.GroupLayout(jPanelServerList);
        jPanelServerList.setLayout(jPanelServerListLayout);
        jPanelServerListLayout.setHorizontalGroup(
            jPanelServerListLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 553, Short.MAX_VALUE)
        );
        jPanelServerListLayout.setVerticalGroup(
            jPanelServerListLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 290, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(jPanelServerList);

        org.jdesktop.layout.GroupLayout jPanelMainLayout = new org.jdesktop.layout.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .add(jSplitPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanelMain);

        jMenuFile.setText("File");

        jMenuItemPreference.setMnemonic('P');
        jMenuItemPreference.setText("Preference");
        jMenuFile.add(jMenuItemPreference);
        jMenuFile.add(jSeparator1);

        jMenuItemQuit.setMnemonic('Q');
        jMenuItemQuit.setText("Quit");
        jMenuItemQuit.setToolTipText("Quit Application");
        jMenuItemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemQuit);

        jMenuBar1.add(jMenuFile);

        jMenuEdit.setText("Edit");

        jMenuItemAbout.setMnemonic('A');
        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuItemAbout);

        jMenuBar1.add(jMenuEdit);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("MongoAnalyzer Description");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitActionPerformed
        http://docs.oracle.com/javase/tutorial/uiswing/components/frame.html
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//        System.exit(0);
    }//GEN-LAST:event_jMenuItemQuitActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        AboutDialog abt = new AboutDialog(this, rootPaneCheckingEnabled);
        abt.setVisible(true);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jButtonAddServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddServerActionPerformed
        AddServerConfigDialog ads = new AddServerConfigDialog(this, rootPaneCheckingEnabled);
        ads.setVisible(rootPaneCheckingEnabled);
        drawMongoServers();
    }//GEN-LAST:event_jButtonAddServerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("******* closing MongoAnalyzer Window. ****.");
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MongoAnalyzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MongoAnalyzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MongoAnalyzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MongoAnalyzer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MongoAnalyzer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddServer;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemPreference;
    private javax.swing.JMenuItem jMenuItemQuit;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelServerList;
    private javax.swing.JPanel jPanelToolbar;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public void drawMongoServers() {
        jPanelServerList.setLayout(new GridLayout());

        jPanelServerList.removeAll();
        //Now, show the MongoServers.
        //Map<?, ?> map = MongoServerConfig.serverlist;
        //for (Entry<?, ?> ms : map.entrySet()) {
        for (Entry<String, MongoServerConfig> ms : MongoServerConfigFactory.serverlist.entrySet()) {
            final MongoServerIcon mongo_server_button = new MongoServerIcon();
            final String server_alias = ms.getKey().toString();
            mongo_server_button.setText(server_alias);
            mongo_server_button.setVerticalTextPosition(SwingConstants.BOTTOM);
            mongo_server_button.setHorizontalTextPosition(SwingConstants.CENTER);

            //Use Box or panel to constraint the button. Otherwise, it fills up the entire panel!
            //JPanel panel4button = new JPanel();
            //panel4button.add(mongo_server);
            Box b = new Box(BoxLayout.Y_AXIS);
            b.add(mongo_server_button);
            this.jPanelServerList.add(b);

            //allows a new Dialog box to pop open.
            mongo_server_button.addMouseListener(new java.awt.event.MouseAdapter() {

                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    // Can we get an instance of the MonogServer
                    try {
                        MongoServerConfig mconfig = MongoServerConfigFactory.getMongoServerConfig(server_alias);
                        MongoServerWrapper mcls = new MongoServerWrapper(mconfig);
                        DetailedServerView dsview = new DetailedServerView(mcls);
                        dsview.setTitle(server_alias);
                        dsview.setVisible(true);
                    } catch (java.net.UnknownHostException e) {
                        ErrorDialog ed = new ErrorDialog(null, rootPaneCheckingEnabled);
                        ed.showErrorMessage(e.getClass() + ": " + e.getMessage());
                        ed.setVisible(true);
                        return;
                    } catch (AuthenticationException e) {
                        ErrorDialog ed = new ErrorDialog(null, rootPaneCheckingEnabled);
                        ed.showErrorMessage("Cannot authenticate, bad username/password.");
                        ed.setVisible(true);
                    } catch (Exception e) {
                        ErrorDialog ed = new ErrorDialog(null, rootPaneCheckingEnabled);
                        ed.showErrorMessage(e.getClass() + ": " + e.getMessage());
                        ed.setVisible(true);
                        return;
                    }
                }
            });
        }

        jPanelServerList.revalidate();
        jPanelServerList.repaint();
    }
}
